package com.aashdit.digiverifier.config.candidate.Enum;

public enum CandidateStatusEnum {
	NEWUPLOAD,
	INVALIDUPLOAD,
	INVITATIONSENT,
	INVITATIONEXPIRED,
	CANCELLED,
	REINVITE,
	PENDINGAPPROVAL,
	FINALREPORT,
	ITR,
	EPFO,
	DIGILOCKER,
	PROCESSDECLINED,
	INTERIMREPORT,
	RELATIVEADDRESS
}
